name: spa-base-quasar

services:
  quasar:
    container_name: spa-base-quasar-dev
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    ports:
      - "9020:9020"
    environment:
      - VITE_API_URL=http://localhost:8097
    volumes:
      - .:/app
      - quasar_node_modules:/app/node_modules
    develop:
      watch:
        - path: ./src
          target: /app/src
          action: sync
        - path: ./package.json
          target: /app/package.json
          action: restart
        - path: ./quasar.config.ts
          target: /app/quasar.config.ts
          action: restart

volumes:
  quasar_node_modules:
